services:
  app:
    build: 
      context: .
      target: builder
      dockerfile: Dockerfile
    volumes:
      - .:/avantsoft_app
      - bundle_data:/usr/local/bundle
    ports:
      - "${RAILS_PORT}:3000"
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: avantsoft
    command: >
      sh -c "if [ ! -f Gemfile ]; then
               rails new . --database=postgresql --skip-bundle --force &&
               bundle install;
             fi &&
             rails server -b 0.0.0.0 -p 3000"

  db:
    image: postgres:17.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"

volumes:
  bundle_data:
  postgres_data:
