# PostgreSQL Configuration
# See: https://guides.rubyonrails.org/configuring.html#configuring-a-database

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_TEST", ENV.fetch("POSTGRES_DB")) %>

staging:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
